# Available settings to override the default behavior for each plugin are
# commented out. The only required setting if you want to use a plugin is
# enabled = true

[ tool.beeblebrox]

  [ tool.beeblebrox.circleci_artifacts ]

    # enabled = true

  [ tool.beeblebrox.milestones ]

    # enabled = true
    # missing_message = ""
    # present_message = ""

  [ tool.beeblebrox.pull_requests ]

     enabled = true
    # skip_labels = []
    # skip_fails = true

  [ tool.beeblebrox.towncrier_changelog ]

    enabled = true
    verify_pr_number = True
    changelog_skip_label = "No Changelog required"
    # changelog_exists = ""
    changelog_missing = "Our Lord Apollo demands that you tell him about the changes that you propose! Please add a Changelog!"
    # number_correct = ""
    number_incorrect = "Our Lord Apollo demands that your Changelog entry be numbered the same as your PR number!"
    # type_correct = ""
    # type_incorrect = ""
    # help_url = ""
